name: sso_demo

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=${KC_ADMIN_USERNAME:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWD:-admin}
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - ./configs/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true
    depends_on:
      - openldap
    networks:
      - deploy
      - database

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=${LDAP_ORG:-ExampleOrg}
      - LDAP_DOMAIN=${LDAP_DOMAIN:-example.org}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD:-admin}
    volumes:
      - ldap_data:/var/lib/ldap
      - ./configs/ldap:/etc/ldap/slapd.d
    networks:
      - database
    ports:
      - "389:389"
      - "636:636"


  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "6443:443"
    depends_on:
      - openldap
    networks:
      - database

volumes:
  ldap_data:

networks:
  deploy:
    driver: bridge
  database:
    driver: bridge