name: sso_demo

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=${KC_ADMIN_USERNAME:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWD:-admin}
      - KC_HOSTNAME_STRICT_HTTPS=true
      - KC_CERTIFICATE_FILE=/opt/keycloak/cert/server.crt
      - KC_PRIVATE_KEY_FILE=/opt/keycloak/cert/server.key
      - KC_HTTPS_PROTOCOLS=TLSv1.2,TLSv1.3
      - KC_HTTPS_PORT=443
      - KC_PROXY=edge
    ports:
      - "8443:443"
    volumes:
      - ./configs/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./configs/nginx/ssl/sso.example.org:/opt/keycloak/cert
    command:
      - start
      - --import-realm
      - --hostname=${KC_HOSTNAME:-sso.example.org}
      - --https-port=${KC_HTTPS_PORT:-443}
      - --https-certificate-file=/opt/keycloak/cert/server.crt
      - --https-certificate-key-file=/opt/keycloak/cert/server.key
    depends_on:
      - openldap
    networks:
      - deploy
      - database
    # healthcheck:
    #   test: ["CMD", "curl", "-f",  "https://localhost:8443/realms/demo-sso-realm"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  openldap:
    image: osixia/openldap:latest
    environment:
      - LDAP_ORGANISATION=${LDAP_ORG:-ExampleOrg}
      - LDAP_DOMAIN=${LDAP_DOMAIN:-example.org}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD:-admin}
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./configs/ldap:/etc/ldap/slapd.d
    networks:
      - database
    ports:
      - "389:389"
      - "636:636"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "6443:443"
    depends_on:
      - openldap
    networks:
      - database

  first-app:
    build: ./sites/first.example.site
    restart: unless-stopped
    networks:
      - deploy
    extra_hosts:
      - "sso.example.org:host-gateway"
    # depends_on:
    #   keycloak:
    #     condition: service_healthy

  second-app:
    build: ./sites/second.example.site
    restart: unless-stopped
    networks:
      - deploy
    extra_hosts:
      - "sso.example.org:host-gateway"
    # depends_on:
    #   keycloak:
    #     condition: service_healthy

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/sites-available:/etc/nginx/sites-available
      - ./configs/nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
      - first-app
      - second-app
    networks:
      - deploy

networks:
  deploy:
    driver: bridge
  database:
    driver: bridge
